name: holoanalytics_mini
version: "1.0"
profile: holoanalytics
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  holoanalytics_mini:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics